import type { Metadata } from "next";
import Link from "next/link";
import { Archive, ArrowRight, CalendarDays, CheckCircle2, Dumbbell, RotateCcw, Sparkles } from "lucide-react";

import { activateTemplate, restorePlan } from "@/app/actions";
import { ArchivePlanButton } from "@/components/archive-plan-button";
import { PlanSwitcher } from "@/components/plan-switcher";
import { SubmitButton } from "@/components/submit-button";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { getActivePlan, getArchivedPlans, getPlanTemplates, getUserPlans } from "@/lib/data";
import { requireUser } from "@/lib/session";

export const metadata: Metadata = { title: "Plan library" };
const goalLabels = { build_muscle: "Muscle", lose_fat: "Fat loss", get_stronger: "Strength", general_fitness: "All-round" };

export default async function PlansPage() {
  const user = await requireUser();
  const [templates, activePlan, userPlans, archivedPlans] = await Promise.all([getPlanTemplates(), getActivePlan(user.id), getUserPlans(user.id), getArchivedPlans(user.id)]);

  return <div className="space-y-8">
    <div className="max-w-3xl"><p className="flex items-center gap-2 text-sm font-medium text-primary"><Sparkles className="size-4" /> Your plan workspace</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Train for more than one target</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">Keep separate routines for muscle, strength, fat loss, or general fitness. Archive plans you are finished with without losing exercises, notes, or workout history.</p></div>

    {userPlans.length > 0 ? <Card className="border-primary/30 bg-primary/5"><CardHeader className="gap-4 sm:flex-row sm:items-center sm:justify-between"><div><CardTitle className="text-lg">Active plans</CardTitle><CardDescription className="mt-1">{userPlans.length} active {userPlans.length === 1 ? "plan" : "plans"} · choose which one is current</CardDescription></div>{activePlan && <PlanSwitcher plans={userPlans.map(({ id, name, goal }) => ({ id, name, goal }))} currentPlanId={activePlan.id} />}</CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{userPlans.map((plan) => <div key={plan.id} className={`rounded-xl border p-4 ${plan.isCurrent ? "border-primary/40 bg-background" : "bg-muted/15"}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate font-medium">{plan.name}</p><p className="mt-1 text-xs text-muted-foreground">{goalLabels[plan.goal]} · {plan.daysPerWeek} days · {plan.durationWeeks} weeks</p></div><div className="flex items-center gap-1">{plan.isCurrent && <Badge>Current</Badge>}<ArchivePlanButton id={plan.id} name={plan.name} isCurrent={plan.isCurrent} /></div></div><p className="mt-3 text-xs text-muted-foreground">{plan.workoutCount} training days · {plan.exerciseCount} exercises</p></div>)}</CardContent></Card> : <Card className="border-dashed"><CardContent className="py-10 text-center"><Archive className="mx-auto size-6 text-primary" /><p className="mt-3 font-medium">No active plans</p><p className="mt-1 text-sm text-muted-foreground">Restore an archived plan or add a fresh template below.</p></CardContent></Card>}

    {archivedPlans.length > 0 && <Card className="border-white/8"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Archive className="size-4 text-primary" /> Archived plans</CardTitle><CardDescription>Kept out of your active rotation while all workout history remains in analytics.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{archivedPlans.map((plan) => <div key={plan.id} className="rounded-xl border bg-muted/10 p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate font-medium">{plan.name}</p><p className="mt-1 text-xs text-muted-foreground">{goalLabels[plan.goal]} · {plan.daysPerWeek} days · {plan.workoutCount} training days</p></div><Badge variant="outline">Archived</Badge></div><form action={restorePlan} className="mt-4"><input type="hidden" name="planId" value={plan.id} /><SubmitButton size="sm" variant="outline" className="w-full" pendingLabel="Restoring…"><RotateCcw /> Restore plan</SubmitButton></form></div>)}</CardContent></Card>}

    <div><p className="text-sm font-medium text-primary">Create another plan</p><h2 className="mt-1 text-2xl font-semibold tracking-tight">Evidence-informed templates</h2><p className="mt-2 text-sm text-muted-foreground">Each template creates a new private copy and makes it current. Your existing plans remain available.</p></div>
    <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{templates.map((template) => { const active = activePlan?.sourceTemplateId === template.id; return <Card key={template.id} className={active ? "border-primary/40 bg-primary/5" : "border-white/8"}><CardHeader><div className="flex items-start justify-between gap-3"><div className="flex flex-wrap gap-2"><Badge>{template.daysPerWeek} days</Badge><Badge variant="secondary">{template.experience}</Badge>{template.dietFit === "vegan" && <Badge variant="outline">Vegan focus</Badge>}</div>{active && <CheckCircle2 className="size-5 text-primary" />}</div><CardTitle className="mt-3">{template.title}</CardTitle><CardDescription className="leading-6">{template.description}</CardDescription></CardHeader><CardContent><div className="mb-5 flex items-center justify-between rounded-lg bg-muted/35 px-3 py-2 text-sm"><span className="flex items-center gap-2"><CalendarDays className="size-4 text-primary" />{template.durationWeeks} weeks</span><span>{goalLabels[template.goal]}</span></div><div className="flex gap-2"><Button className="flex-1" variant="outline" asChild><Link href={`/app/plans/${template.slug}`}>View schedule <ArrowRight /></Link></Button><form action={activateTemplate} className="flex-1"><input type="hidden" name="templateSlug" value={template.slug} /><SubmitButton className="w-full" pendingLabel="Creating…"><Dumbbell /> {active ? "Add another" : "Add plan"}</SubmitButton></form></div></CardContent></Card>; })}</div>
    <Card className="border-amber-400/20 bg-amber-400/5"><CardContent className="p-5 text-sm leading-6 text-muted-foreground"><span className="font-medium text-foreground">Recovery guardrail:</span> five- and six-day plans are not automatically better. Start them only when your training experience, sleep, and schedule support them; otherwise the two-to-four-day plans can produce excellent results.</CardContent></Card>
  </div>;
}
