import Link from "next/link";
import { ArrowRight, CalendarDays, Dumbbell, Flame, Salad, Scale, Sparkles, Trophy } from "lucide-react";

import { startWorkout } from "@/app/actions";
import { SubmitButton } from "@/components/submit-button";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { getDashboardData } from "@/lib/data";
import { requireUser } from "@/lib/session";

export default async function DashboardPage() {
  const user = await requireUser();
  const data = await getDashboardData(user.id);
  if (!data.profile?.onboardingComplete) return <div className="mx-auto max-w-2xl py-16 text-center"><div className="mx-auto grid size-12 place-items-center rounded-2xl bg-primary/15 text-primary"><Sparkles /></div><h1 className="mt-5 text-3xl font-semibold tracking-tight">Let’s build your baseline</h1><p className="mx-auto mt-3 max-w-lg text-muted-foreground">Answer a focused assessment so training volume, schedule, and starting nutrition targets fit you.</p><Button className="mt-7" size="lg" asChild><Link href="/app/onboarding">Start assessment <ArrowRight /></Link></Button></div>;
  const nextWorkout = data.plan?.workouts[data.completedWorkouts % Math.max(1, data.plan.workouts.length)];
  return <div className="space-y-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm text-primary">Your training cockpit</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Ready, {user.name.split(" ")[0]}?</h1><p className="mt-2 text-sm text-muted-foreground">Keep today’s promise small and specific.</p></div><Badge variant="outline" className="w-fit"><CalendarDays className="size-3" /> Week {(data.completedWorkouts % 8) + 1} of 8</Badge></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[[Dumbbell,String(data.completedWorkouts),'workouts complete'],[Scale,data.latestMeasurement ? `${data.latestMeasurement.weightKg} kg` : `${data.profile.currentWeightKg} kg`,'latest weight'],[Flame,String(data.profile.calorieTarget ?? '—'),'daily kcal target'],[Salad,`${data.profile.proteinTargetG ?? '—'} g`,'protein target']].map(([Icon,value,label]) => { const C=Icon as typeof Dumbbell; return <Card key={String(label)} className="border-white/8"><CardContent className="flex items-start justify-between p-5"><div><p className="text-2xl font-semibold">{String(value)}</p><p className="mt-1 text-xs text-muted-foreground">{String(label)}</p></div><span className="grid size-9 place-items-center rounded-xl bg-primary/10 text-primary"><C className="size-4" /></span></CardContent></Card>; })}</div>
    <div className="grid gap-6 xl:grid-cols-[1.35fr_.65fr]">
      <Card className="overflow-hidden border-primary/20 bg-[linear-gradient(135deg,var(--card),oklch(0.22_0.035_155))]"><CardHeader><div className="flex items-center justify-between"><div><p className="text-xs font-medium uppercase tracking-[0.16em] text-primary">Up next</p><CardTitle className="mt-2 text-2xl">{nextWorkout?.title ?? "Your next workout"}</CardTitle><CardDescription className="mt-1">{nextWorkout?.focus}</CardDescription></div><div className="grid size-12 place-items-center rounded-2xl bg-primary text-primary-foreground"><Dumbbell /></div></div></CardHeader><CardContent>{nextWorkout ? <><div className="space-y-3">{nextWorkout.exercises.slice(0,4).map((item) => <div key={item.id} className="flex items-center justify-between rounded-lg border border-white/8 bg-background/25 px-4 py-3"><span className="text-sm font-medium">{item.name}</span><span className="text-xs text-muted-foreground">{item.sets} × {item.repMin}–{item.repMax}</span></div>)}</div><form action={startWorkout} className="mt-5"><input type="hidden" name="workoutId" value={nextWorkout.id} /><SubmitButton size="lg" className="w-full" pendingLabel="Starting workout…">Start workout <ArrowRight /></SubmitButton></form></> : <Button asChild><Link href="/app/plan">Open my plan</Link></Button>}</CardContent></Card>
      <Card className="border-white/8"><CardHeader><CardTitle className="text-base">Block progress</CardTitle><CardDescription>Consistency across this 8-week foundation</CardDescription></CardHeader><CardContent><div className="flex items-end justify-between"><span className="text-3xl font-semibold">{Math.min(100, Math.round((data.completedWorkouts / Math.max(1,(data.plan?.daysPerWeek ?? 3) * 8)) * 100))}%</span><Trophy className="size-5 text-primary" /></div><Progress className="mt-4" value={Math.min(100, (data.completedWorkouts / Math.max(1,(data.plan?.daysPerWeek ?? 3) * 8)) * 100)} /><p className="mt-4 text-xs leading-5 text-muted-foreground">A completed session beats a perfect session that never starts.</p><Button variant="outline" className="mt-5 w-full" asChild><Link href="/app/progress">View progress</Link></Button></CardContent></Card>
    </div>
    <Card className="border-white/8"><CardHeader><CardTitle className="text-base">Recent sessions</CardTitle></CardHeader><CardContent>{data.recentSessions.length ? <div className="divide-y">{data.recentSessions.map((session) => <div key={session.id} className="flex items-center justify-between py-3"><div><p className="text-sm font-medium">{session.title}</p><p className="text-xs text-muted-foreground">{session.startedAt.toLocaleDateString()}</p></div><Badge variant={session.completedAt ? "secondary" : "outline"}>{session.completedAt ? "Completed" : "In progress"}</Badge></div>)}</div> : <p className="text-sm text-muted-foreground">Your completed workouts will appear here.</p>}</CardContent></Card>
  </div>;
}
